development:
  adapter: postgresql
  database: swidjit_dev
  username: sonny
  timeout: 5000

test: &TEST
  adapter: postgresql
  database: swidjit_test
  username: sonny
  timeout: 5000
  min_messages: warning
